version: '3.1'

services:
  hapi-db:
    image: postgres
    shm_size: 1g
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: hapi
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    command: -c listen_addresses='*'
    volumes:
      - hapi-db:/var/lib/postgresql/data

  hapi-jpa:
    image: knoppiks/hapi-jpa
    ports:
      - 8080:8080
    environment:
      CATALINA_OPTS: -Dhapi.properties=/hapi.properties
    volumes:
      - ./hapi_jpa/hapi.properties:/hapi.properties
    links:
      - hapi-db

volumes:
  hapi-db:
    external: true
