version: '3.1'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./csv_db:/docker-entrypoint-initdb.d
      - ./synthea/output/csv:/csv

  hapi_jpa:
    image: knoppiks/hapi-jpa
    ports:
      - 80:8080
    volumes:
      - ./synthea/output/fhir:/fhir
      - ./scripts:/scripts